### ISSUE TITLE
Can't open files requiring x509 when run in Docker for Windows

### ISSUE THREAD

**Issue by ivukotic** [root-project/root-docker#39]
When running the latest ROOT image in docker in Windows (WSL2), I can open TFile if remote server does not require authentication. If it does require x509 authentication, it fails:
eg.
  f=TFile::Open("root://xrootd-at2-door.pic.es:1094//pnfs/pic.es/IFAEAtlasTier2/t2atlasdatadisk/rucio/mc16_13TeV/2e/da/AOD.20798297._000879.pool.root.1")
Error in <TNetXNGFile::Open>: [FATAL] Auth failed

**Comment by eguiraud** [comment]
Hi @ivukotic , which docker image are you using, and does it only happen when running it in WSL2?

**Comment by ivukotic** [comment]
Hi,
It appears I forgot to install CAs (:facepalm:).
Sorry for the noise.
Cheers,
Ilija
