### ISSUE TITLE
Feature request: Support for OpenSUSE docker images

### ISSUE THREAD

**Issue by xcorat** [root-project/root-docker#46]
CentOS seem to be dying and I prefer SUSE over Canonical and OpenSUSE over Ubuntu. Both in terms of open source philosophy ease of maintenance.

Do you plan on supporting OpenSUSE? 

I understand there are some roadblocks compared to other distros (I don't see compiled packages for OpenSUSE on root installation page either), but it would be really nice if you have more support officially.

**Comment by eguiraud** [comment]
This is probably a good starting point: https://github.com/root-project/root-docker/tree/master/ubuntu_from_source

**Comment by eguiraud** [comment]
Closing: as discussed, we do not plan to provide recipes for openSUSE but we'd be glad to merge a PR with the corresponding Dockerfile if the community provides it.
